#!/usr/bin/env bash

set -e

ARCHIVE_DIR="files"
ARCHIVE_TYPE=".tar.gz"
ARCHIVE_NAME="${ARCHIVE_DIR}${ARCHIVE_TYPE}"

bwd=$(pwd)
tar -xzf "$ARCHIVE_NAME"
rm -rf "$ARCHIVE_NAME"
cd "$ARCHIVE_DIR"
./run
cd "$bwd"
tar -czf "$ARCHIVE_NAME" "$ARCHIVE_DIR"
rm -rf "$ARCHIVE_DIR"
